import { Country } from '@/types'

export const COUNTRIES: Country[] = [
  {
    name: 'Hà Nội',
    flag: '/vietnam.png',
    coordinates: [21.0285, 105.8542],
    zoom: 6,
  },
  {
    name: 'Trường Sa',
    flag: '/vietnam.png',
    coordinates: [10.4167, 114.3667],
    zoom: 6,
  },
  {
    name: 'Hoàng Sa',
    flag: '/vietnam.png',
    coordinates: [16.8333, 112.3333],
    zoom: 6,
  },
  {
    name: 'Châu Âu',
    flag: '/eu.png',
    coordinates: [50.8503, 4.3517],
    zoom: 6,
  },
  {
    name: 'Úc',
    flag: '/australia.png',
    coordinates: [-35.2809, 149.13],
    zoom: 6,
  },
  {
    name: 'New Zealand',
    flag: '/new-zealand.png',
    coordinates: [-41.2865, 174.7762],
    zoom: 6,
  },
  {
    name: 'Caribe',
    flag: '/caribe.png',
    coordinates: [18.2208, -66.5901],
    zoom: 6,
  },
  {
    name: 'Mỹ',
    flag: '/us.png',
    coordinates: [38.9072, -77.0369],
    zoom: 6,
  },
  {
    name: 'Canada',
    flag: '/canada.png',
    coordinates: [45.4215, -75.6972],
    zoom: 6,
  },
]

export const SPECIAL_COUNTRIES = [
  'Australia',
  'Canada',
  'United States of America',
  'Austria',
  'Belgium',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Netherlands',
  'Poland',
  'Portugal',
  'Romania',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'New Zealand',
  // "Puerto Rico",
]
